name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          CODE_LANG: text
          TIME_RANGE: all_time
          LANG_COUNT: 25
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: Prisma "GitIgnore file" Other Markdown SCSS Image svg "Git Config" Dart Text XML Groovy Docker "Java Properties" textmate mcfunction Bash YAML SQL TSConfig "Image (svg)"
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          TARGET_BRANCH: main
          TARGET_PATH: README.MD
          COMMITTER_NAME: yanzz231
          COMMITTER_EMAIL: mrpartys05@gmail.com
          AUTHOR_NAME: Yanzz231
          AUTHOR_EMAIL: mrpartys05@gmail.com
      
      - name: Check and commit
        run: |
          git config user.name 'Yanzz231'
          git config user.email 'mrpartys05@gmail.com'
          
          # Cek ada perubahan atau nggak
          if git diff-index --quiet HEAD --; then
            git commit --allow-empty -m "Updated waka-readme graph with new metrics"
          fi
          
          git push
